/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistem_Kasir;

import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gibra
 */
public class Sistem_Kasir extends javax.swing.JFrame {
    connection d = new connection();
    String user;

    
    public Sistem_Kasir() {
        initComponents();
        
    }
    public Sistem_Kasir(String _user){
        initComponents();
        this.user=_user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField14 = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAyamGeprek = new javax.swing.JButton();
        btnSayurAsem = new javax.swing.JButton();
        btnRendang = new javax.swing.JButton();
        btnKetoprak = new javax.swing.JButton();
        btnGudeg = new javax.swing.JButton();
        btnPempek = new javax.swing.JButton();
        btnGado = new javax.swing.JButton();
        btnNasiUduk = new javax.swing.JButton();
        btnSateMadura = new javax.swing.JButton();
        btnGulai = new javax.swing.JButton();
        btnSeblak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        chkAyamGeprek = new javax.swing.JCheckBox();
        txtAyamGeprek = new java.awt.TextField();
        chkSayurAsem = new javax.swing.JCheckBox();
        txtSayurAsem = new java.awt.TextField();
        chkRendang = new javax.swing.JCheckBox();
        txtRendang = new java.awt.TextField();
        chkKetoprak = new javax.swing.JCheckBox();
        txtKetoprak = new java.awt.TextField();
        chkGudeg = new javax.swing.JCheckBox();
        txtGudeg = new java.awt.TextField();
        chkGulai = new javax.swing.JCheckBox();
        txtGulai = new java.awt.TextField();
        chkSateMadura = new javax.swing.JCheckBox();
        txtSateMadura = new java.awt.TextField();
        chkNasiUduk = new javax.swing.JCheckBox();
        txtNasiUduk = new java.awt.TextField();
        chkGado = new javax.swing.JCheckBox();
        txtGado = new java.awt.TextField();
        chkPempek = new javax.swing.JCheckBox();
        txtPempek = new java.awt.TextField();
        chkSeblak = new javax.swing.JCheckBox();
        txtSeblak = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPajak = new java.awt.TextField();
        txtSubTotal = new java.awt.TextField();
        txtTotal = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceiptArea = new javax.swing.JTextArea();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        textField14.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAyamGeprek.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAyamGeprek.setText("Ayam Geprek");
        btnAyamGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyamGeprekActionPerformed(evt);
            }
        });

        btnSayurAsem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSayurAsem.setText("Sayur Asem");
        btnSayurAsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSayurAsemActionPerformed(evt);
            }
        });

        btnRendang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnRendang.setText("Rendang");
        btnRendang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendangActionPerformed(evt);
            }
        });

        btnKetoprak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnKetoprak.setText("Ketoprak");
        btnKetoprak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetoprakActionPerformed(evt);
            }
        });

        btnGudeg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGudeg.setText("Gudeg");
        btnGudeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGudegActionPerformed(evt);
            }
        });

        btnPempek.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPempek.setText("Pempek");
        btnPempek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPempekActionPerformed(evt);
            }
        });

        btnGado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGado.setText("Gado-Gado");
        btnGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadoActionPerformed(evt);
            }
        });

        btnNasiUduk.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnNasiUduk.setText("Nasi Uduk");
        btnNasiUduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNasiUdukActionPerformed(evt);
            }
        });

        btnSateMadura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSateMadura.setText("Sate Madura");
        btnSateMadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSateMaduraActionPerformed(evt);
            }
        });

        btnGulai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGulai.setText("Gulai");
        btnGulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGulaiActionPerformed(evt);
            }
        });

        btnSeblak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSeblak.setText("Seblak");
        btnSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeblakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAyamGeprek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSayurAsem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRendang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKetoprak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGudeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPempek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNasiUduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSateMadura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGulai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeblak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAyamGeprek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSayurAsem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRendang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKetoprak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGudeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPempek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNasiUduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSateMadura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeblak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        chkAyamGeprek.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkAyamGeprek.setText("Ayam Geprek");
        chkAyamGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyamGeprekActionPerformed(evt);
            }
        });

        txtAyamGeprek.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAyamGeprek.setName(""); // NOI18N
        txtAyamGeprek.setText("0");
        txtAyamGeprek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAyamGeprekKeyTyped(evt);
            }
        });

        chkSayurAsem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkSayurAsem.setText("Sayur Asem");
        chkSayurAsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSayurAsemActionPerformed(evt);
            }
        });

        txtSayurAsem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSayurAsem.setText("0");
        txtSayurAsem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSayurAsemKeyTyped(evt);
            }
        });

        chkRendang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkRendang.setText("Rendang");
        chkRendang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRendangActionPerformed(evt);
            }
        });

        txtRendang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRendang.setText("0");
        txtRendang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRendangKeyTyped(evt);
            }
        });

        chkKetoprak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkKetoprak.setText("Ketoprak");
        chkKetoprak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKetoprakActionPerformed(evt);
            }
        });

        txtKetoprak.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKetoprak.setText("0");
        txtKetoprak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKetoprakKeyTyped(evt);
            }
        });

        chkGudeg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkGudeg.setText("Gudeg");
        chkGudeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGudegActionPerformed(evt);
            }
        });

        txtGudeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGudeg.setText("0");
        txtGudeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGudegKeyTyped(evt);
            }
        });

        chkGulai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkGulai.setText("Gulai");
        chkGulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGulaiActionPerformed(evt);
            }
        });

        txtGulai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGulai.setText("0");
        txtGulai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGulaiKeyTyped(evt);
            }
        });

        chkSateMadura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkSateMadura.setText("Sate Madura");
        chkSateMadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateMaduraActionPerformed(evt);
            }
        });

        txtSateMadura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSateMadura.setText("0");
        txtSateMadura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSateMaduraKeyTyped(evt);
            }
        });

        chkNasiUduk.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkNasiUduk.setText("Nasi Uduk");
        chkNasiUduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiUdukActionPerformed(evt);
            }
        });

        txtNasiUduk.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNasiUduk.setText("0");
        txtNasiUduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNasiUdukKeyTyped(evt);
            }
        });

        chkGado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkGado.setText("Gado-Gado");
        chkGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGadoActionPerformed(evt);
            }
        });

        txtGado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGado.setText("0");
        txtGado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGadoKeyTyped(evt);
            }
        });

        chkPempek.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkPempek.setText("Pempek");
        chkPempek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPempekActionPerformed(evt);
            }
        });

        txtPempek.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPempek.setText("0");
        txtPempek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPempekKeyTyped(evt);
            }
        });

        chkSeblak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chkSeblak.setText("Seblak");
        chkSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSeblakActionPerformed(evt);
            }
        });

        txtSeblak.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSeblak.setText("0");
        txtSeblak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeblakKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAyamGeprek)
                    .addComponent(chkSayurAsem)
                    .addComponent(chkRendang)
                    .addComponent(chkKetoprak)
                    .addComponent(chkGudeg)
                    .addComponent(chkPempek)
                    .addComponent(chkGado)
                    .addComponent(chkNasiUduk)
                    .addComponent(chkSateMadura)
                    .addComponent(chkGulai)
                    .addComponent(chkSeblak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAyamGeprek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSayurAsem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRendang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKetoprak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGudeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPempek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNasiUduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSateMadura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSeblak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkAyamGeprek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAyamGeprek, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSayurAsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSayurAsem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRendang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkRendang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKetoprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkKetoprak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGudeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGudeg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPempek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPempek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNasiUduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkNasiUduk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSateMadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSateMadura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGulai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSeblak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSeblak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtAyamGeprek.getAccessibleContext().setAccessibleName("");
        txtAyamGeprek.getAccessibleContext().setAccessibleDescription("");
        txtSayurAsem.getAccessibleContext().setAccessibleName("");
        txtSayurAsem.getAccessibleContext().setAccessibleDescription("");
        txtRendang.getAccessibleContext().setAccessibleName("");
        txtRendang.getAccessibleContext().setAccessibleDescription("");
        txtKetoprak.getAccessibleContext().setAccessibleName("");
        txtKetoprak.getAccessibleContext().setAccessibleDescription("");
        txtGudeg.getAccessibleContext().setAccessibleName("");
        txtGudeg.getAccessibleContext().setAccessibleDescription("");
        txtGulai.getAccessibleContext().setAccessibleName("");
        txtGulai.getAccessibleContext().setAccessibleDescription("");
        txtSateMadura.getAccessibleContext().setAccessibleName("");
        txtSateMadura.getAccessibleContext().setAccessibleDescription("");
        txtNasiUduk.getAccessibleContext().setAccessibleName("");
        txtNasiUduk.getAccessibleContext().setAccessibleDescription("");
        txtGado.getAccessibleContext().setAccessibleName("");
        txtGado.getAccessibleContext().setAccessibleDescription("");
        txtPempek.getAccessibleContext().setAccessibleName("");
        txtPempek.getAccessibleContext().setAccessibleDescription("");
        txtSeblak.getAccessibleContext().setAccessibleName("");
        txtSeblak.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kuantitas");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pajak");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total");

        txtPajak.setName(""); // NOI18N

        txtSubTotal.setName(""); // NOI18N

        txtTotal.setName(""); // NOI18N

        txtReceiptArea.setColumns(20);
        txtReceiptArea.setRows(5);
        jScrollPane1.setViewportView(txtReceiptArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtPajak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtPajak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Makanan");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Kasir Prikitiwtralala");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private JFrame frame; 
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Konfirmasi jika ingin keluar", "Program Kasir Prikitiwtralala", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        /*
            Nama-nama produk
            Ayam Geprek
            Sayur Asem
            Rendang
            Ketoprak
            Gudek
            Pempek
            Gado-Gado
            NasiUduk
            SateMadura
            Gulai
            Seblak
        */
               
        //Untuk Mereset Semua TextField, CheckBox
        
        //Textbox Pembayaran
        txtPajak.setText("0");
        txtSubTotal.setText("0");
        txtTotal.setText("0");
        
        // Kode Dibawah untuk RESET nomer yang ada di textbox
        txtAyamGeprek.setText("0");
        txtSayurAsem.setText("0");
        txtRendang.setText("0");
        txtKetoprak.setText("0");
        txtGudeg.setText("0");
        txtPempek.setText("0");
        txtGado.setText("0");
        txtNasiUduk.setText("0");
        txtSateMadura.setText("0");
        txtGulai.setText("0");
        txtSeblak.setText("0");
        
        // Kode Dibawah untuk DEACTIVE Text box
        txtAyamGeprek.setEnabled(false);
        txtSayurAsem.setEnabled(false);
        txtRendang.setEnabled(false);
        txtKetoprak.setEnabled(false);
        txtGudeg.setEnabled(false);
        txtPempek.setEnabled(false);
        txtGado.setEnabled(false);
        txtNasiUduk.setEnabled(false);
        txtSateMadura.setEnabled(false);
        txtGulai.setEnabled(false);
        txtSeblak.setEnabled(false);

        // Kode Dibawah untuk DEACTIVE check box yang di select saja
        chkAyamGeprek.setSelected(false);
        chkSayurAsem.setSelected(false);
        chkRendang.setSelected(false);
        chkKetoprak.setSelected(false);
        chkGudeg.setSelected(false);
        chkPempek.setSelected(false);
        chkGado.setSelected(false);
        chkNasiUduk.setSelected(false);
        chkSateMadura.setSelected(false);
        chkGulai.setSelected(false);
        chkSeblak.setSelected(false);
        
        // Kode Dibawah untuk DEACTIVE check box untuk semua bagian
        chkAyamGeprek.setEnabled(false);
        chkSayurAsem.setEnabled(false);
        chkRendang.setEnabled(false);
        chkKetoprak.setEnabled(false);
        chkGudeg.setEnabled(false);
        chkPempek.setEnabled(false);
        chkGado.setEnabled(false);
        chkNasiUduk.setEnabled(false);
        chkSateMadura.setEnabled(false);
        chkGulai.setEnabled(false);
        chkSeblak.setEnabled(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtAyamGeprekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAyamGeprekKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtAyamGeprekKeyTyped

    private void txtSayurAsemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSayurAsemKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtSayurAsemKeyTyped

    private void txtRendangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRendangKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRendangKeyTyped

    private void txtKetoprakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKetoprakKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtKetoprakKeyTyped

    private void txtGudegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGudegKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtGudegKeyTyped

    private void txtPempekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPempekKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPempekKeyTyped

    private void txtGadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGadoKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtGadoKeyTyped

    private void txtNasiUdukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNasiUdukKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNasiUdukKeyTyped

    private void txtSateMaduraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSateMaduraKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtSateMaduraKeyTyped

    private void txtGulaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGulaiKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtGulaiKeyTyped

    private void txtSeblakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeblakKeyTyped
        //Kodingan ini digunakan hanya untuk mengetik Angka/Number pada TextField
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE) ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtSeblakKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /*
            Nama-nama produk
            Ayam Geprek
            Sayur Asem
            Rendang
            Ketoprak
            Gudeg
            Pempek
            Gado-Gado
            NasiUduk
            SateMadura
            Gulai
            Seblak
        */
        
        //Kodingan ini untuk Mematikan fungsi atau DEACTIVATE Textbox
        txtAyamGeprek.setEnabled(false);
        txtSayurAsem.setEnabled(false);
        txtRendang.setEnabled(false);
        txtKetoprak.setEnabled(false);
        txtGudeg.setEnabled(false);
        txtPempek.setEnabled(false);
        txtGado.setEnabled(false);
        txtNasiUduk.setEnabled(false);
        txtSateMadura.setEnabled(false);
        txtGulai.setEnabled(false);
        txtSeblak.setEnabled(false);
        txtPajak.setEnabled(false);
        txtSubTotal.setEnabled(false);
        txtTotal.setEnabled(false);
        txtReceiptArea.setEnabled(false);
        
        //Kodingan ini untuk Mematikan fungsi atau DEACTIVATE CheckBox
        chkAyamGeprek.setEnabled(false);
        chkSayurAsem.setEnabled(false);
        chkRendang.setEnabled(false);
        chkKetoprak.setEnabled(false);
        chkGudeg.setEnabled(false);
        chkPempek.setEnabled(false);
        chkGado.setEnabled(false);
        chkNasiUduk.setEnabled(false);
        chkSateMadura.setEnabled(false);
        chkGulai.setEnabled(false);
        chkSeblak.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void btnAyamGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyamGeprekActionPerformed
        chkAyamGeprek.setEnabled(true);
    }//GEN-LAST:event_btnAyamGeprekActionPerformed

    private void btnSayurAsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSayurAsemActionPerformed
        chkSayurAsem.setEnabled(true);
    }//GEN-LAST:event_btnSayurAsemActionPerformed

    private void btnRendangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendangActionPerformed
        chkRendang.setEnabled(true);
    }//GEN-LAST:event_btnRendangActionPerformed

    private void btnKetoprakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetoprakActionPerformed
        chkKetoprak.setEnabled(true);
    }//GEN-LAST:event_btnKetoprakActionPerformed

    private void btnGudegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGudegActionPerformed
        chkGudeg.setEnabled(true);
    }//GEN-LAST:event_btnGudegActionPerformed

    private void btnPempekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPempekActionPerformed
        chkPempek.setEnabled(true);
    }//GEN-LAST:event_btnPempekActionPerformed

    private void btnGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadoActionPerformed
        chkGado.setEnabled(true);
    }//GEN-LAST:event_btnGadoActionPerformed

    private void btnNasiUdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNasiUdukActionPerformed
        chkNasiUduk.setEnabled(true);
    }//GEN-LAST:event_btnNasiUdukActionPerformed

    private void btnSateMaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSateMaduraActionPerformed
        chkSateMadura.setEnabled(true);
    }//GEN-LAST:event_btnSateMaduraActionPerformed

    private void btnGulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGulaiActionPerformed
        chkGulai.setEnabled(true);
    }//GEN-LAST:event_btnGulaiActionPerformed

    private void btnSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeblakActionPerformed
        chkSeblak.setEnabled(true);
    }//GEN-LAST:event_btnSeblakActionPerformed

    private void chkAyamGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyamGeprekActionPerformed
        if(chkAyamGeprek.isSelected())
        {
            txtAyamGeprek.setEnabled(true);
            txtAyamGeprek.setText("");
            txtAyamGeprek.requestFocus();
        }
        else
        {
            txtAyamGeprek.setEnabled(false);
            txtAyamGeprek.setText("0");
        }
    }//GEN-LAST:event_chkAyamGeprekActionPerformed

    private void chkSayurAsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSayurAsemActionPerformed
        if(chkSayurAsem.isSelected())
        {
            txtSayurAsem.setEnabled(true);
            txtSayurAsem.setText("");
            txtSayurAsem.requestFocus();
            
        }else
        {
            txtSayurAsem.setEnabled(false);
            txtSayurAsem.setText("0");
        }
    }//GEN-LAST:event_chkSayurAsemActionPerformed

    private void chkRendangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRendangActionPerformed
        if(chkRendang.isSelected())
        {
            txtRendang.setEnabled(true);
            txtRendang.setText("");
            txtRendang.requestFocus();
        }else{
            txtRendang.setEnabled(false);
            txtRendang.setText("0");
        }
    }//GEN-LAST:event_chkRendangActionPerformed

    private void chkKetoprakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKetoprakActionPerformed
        if(chkKetoprak.isSelected())
        {
            txtKetoprak.setEnabled(true);
            txtKetoprak.setText("");
            txtKetoprak.requestFocus();
        }else
        {
            txtKetoprak.setEnabled(false);
            txtKetoprak.setText("0");
        }
    }//GEN-LAST:event_chkKetoprakActionPerformed

    private void chkGudegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGudegActionPerformed
        if(chkGudeg.isSelected())
        {
            txtGudeg.setEnabled(true);
            txtGudeg.setText("");
            txtGudeg.requestFocus();
        }else{
            txtGudeg.setEnabled(false);
            txtGudeg.setText("0");
        }
    }//GEN-LAST:event_chkGudegActionPerformed

    private void chkPempekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPempekActionPerformed
        if(chkPempek.isSelected())
        {
            txtPempek.setEnabled(true);
            txtPempek.setText("");
            txtPempek.requestFocus();
        }else{
            txtPempek.setEnabled(false);
            txtPempek.setText("0");
        }
    }//GEN-LAST:event_chkPempekActionPerformed

    private void chkGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGadoActionPerformed
        if(chkGado.isSelected())
        {
            txtGado.setEnabled(true);
            txtGado.setText("");
            txtGado.requestFocus();
        }else{
            txtGado.setEnabled(false);
            txtGado.setText("0");
        }
    }//GEN-LAST:event_chkGadoActionPerformed

    private void chkNasiUdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiUdukActionPerformed
        if(chkNasiUduk.isSelected())
        {
            txtNasiUduk.setEnabled(true);
            txtNasiUduk.setText("");
            txtNasiUduk.requestFocus();
        }else{
            txtNasiUduk.setEnabled(false);
            txtNasiUduk.setText("0");
        }
    }//GEN-LAST:event_chkNasiUdukActionPerformed

    private void chkSateMaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateMaduraActionPerformed
        if(chkSateMadura.isSelected())
        {
            txtSateMadura.setEnabled(true);
            txtSateMadura.setText("");
            txtSateMadura.requestFocus();
        }else{
            txtSateMadura.setEnabled(false);
            txtSateMadura.setText("0");
        }
    }//GEN-LAST:event_chkSateMaduraActionPerformed

    private void chkGulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGulaiActionPerformed
        if(chkGulai.isSelected())
        {
            txtGulai.setEnabled(true);
            txtGulai.setText("");
            txtGulai.requestFocus();
        }else{
            txtGulai.setEnabled(false);
            txtGulai.setText("0");
        }
    }//GEN-LAST:event_chkGulaiActionPerformed

    private void chkSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSeblakActionPerformed
        if(chkSeblak.isSelected())
        {
            txtSeblak.setEnabled(true);
            txtSeblak.setText("");
            txtSeblak.requestFocus();
        }else{
            txtSeblak.setEnabled(false);
            txtSeblak.setText("0");
        }
    }//GEN-LAST:event_chkSeblakActionPerformed

    String iPajak, iSubTotal, iTotal;
    double [] itemcost = new double[15];
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        /*
            Nama-nama produk
            Ayam Geprek
            Sayur Asem
            Rendang
            Ketoprak
            Gudeg
            Pempek
            Gado-Gado
            NasiUduk
            SateMadura
            Gulai
            Seblak
        */
        itemcost[0] = Double.parseDouble(txtAyamGeprek.getText()) * 1.50;
        itemcost[1] = Double.parseDouble(txtSayurAsem.getText()) * 2.50;
        itemcost[2] = Double.parseDouble(txtRendang.getText()) * 3.50;
        itemcost[3] = Double.parseDouble(txtKetoprak.getText()) * 4.50;
        itemcost[4] = Double.parseDouble(txtGudeg.getText()) * 5.50;
        itemcost[5] = Double.parseDouble(txtPempek.getText()) * 6.50; 
        itemcost[6] = Double.parseDouble(txtGado.getText()) * 7.50;
        itemcost[7] = Double.parseDouble(txtNasiUduk.getText()) * 8.50;
        itemcost[8] = Double.parseDouble(txtSateMadura.getText()) * 9.50;
        itemcost[9] = Double.parseDouble(txtGulai.getText()) * 10.50;
        itemcost[10] = Double.parseDouble(txtSeblak.getText()) * 11.50;
        
        itemcost[11] = itemcost[0] + itemcost[2] + itemcost[3] + itemcost[4] + itemcost[5] + itemcost[6];
        itemcost[12] = itemcost[7] + itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11] + itemcost[12];
        
        
        iPajak = String.format("Rp. %.2f", itemcost[12]/100);
        iSubTotal = String.format("Rp. %.2f", itemcost[12]);
        iTotal = String.format("Rp. %.2f", itemcost[12] + (itemcost[12]/100));
        
        txtPajak.setText(iPajak);
        txtSubTotal.setText(iSubTotal);
        txtTotal.setText(iTotal);
        
        txtReceiptArea.setEnabled(true);
        
        int refs = 1325 + (int) (Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
        
        txtReceiptArea.append("\n Sistem Kasir Prikitiwtralala" +
                "\n Refrensi: \t\t\t\t" + refs +
                "\n ==================================================\t" +
                "\n ==================================================\t" +
                "\nPajak:\t\t\t\t" + iPajak +
                "\nSub Total:\t\t\t\t" + iSubTotal +
                "\nTotal:\t\t\t\t" + iTotal +
                "\n ==================================================\t" +
                "\n ==================================================\t" +
                "\nDate: " + Tdate.format(timer.getTime()) + 
                "\t\tTime: " + tTime.format(timer.getTime()) +
                "\n ==================================================\t" +
                "\n ==================================================\t" +
                "\n\n\tTERIMAKASIH SUDAH BERBELANJA"+
                "\n ==================================================\t" +
                "\n ==================================================\t"
        );
        
        
    }//GEN-LAST:event_btnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistem_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistem_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistem_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistem_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistem_Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyamGeprek;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGado;
    private javax.swing.JButton btnGudeg;
    private javax.swing.JButton btnGulai;
    private javax.swing.JButton btnKetoprak;
    private javax.swing.JButton btnNasiUduk;
    private javax.swing.JButton btnPempek;
    private javax.swing.JButton btnRendang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSateMadura;
    private javax.swing.JButton btnSayurAsem;
    private javax.swing.JButton btnSeblak;
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox chkAyamGeprek;
    private javax.swing.JCheckBox chkGado;
    private javax.swing.JCheckBox chkGudeg;
    private javax.swing.JCheckBox chkGulai;
    private javax.swing.JCheckBox chkKetoprak;
    private javax.swing.JCheckBox chkNasiUduk;
    private javax.swing.JCheckBox chkPempek;
    private javax.swing.JCheckBox chkRendang;
    private javax.swing.JCheckBox chkSateMadura;
    private javax.swing.JCheckBox chkSayurAsem;
    private javax.swing.JCheckBox chkSeblak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField textField14;
    private java.awt.TextField txtAyamGeprek;
    private java.awt.TextField txtGado;
    private java.awt.TextField txtGudeg;
    private java.awt.TextField txtGulai;
    private java.awt.TextField txtKetoprak;
    private java.awt.TextField txtNasiUduk;
    private java.awt.TextField txtPajak;
    private java.awt.TextField txtPempek;
    private javax.swing.JTextArea txtReceiptArea;
    private java.awt.TextField txtRendang;
    private java.awt.TextField txtSateMadura;
    private java.awt.TextField txtSayurAsem;
    private java.awt.TextField txtSeblak;
    private java.awt.TextField txtSubTotal;
    private java.awt.TextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
